version: '3.8'

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_vol:

services: 
  mongo-express:
    image: mongo-express:${EXPRESS_TAG}
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongousr
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongopwd
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_OPTIONS_EDITORTHEME=dark
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    restart: always
    networks:
      - mongo_network
    
  mongodb:
    image: mongo:${MONGODB_TAG}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongousr
      - MONGO_INITDB_ROOT_PASSWORD=mongopwd
    volumes:
      - mongodb_vol:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo_network